/* SPDX-License-Identifier: MIT */
/*
 * Copyright 2024 Advanced Micro Devices, Inc.
 *
 */

#ifndef __IGT_COLOR_LUT_H__
#define __IGT_COLOR_LUT_H__

#include "drm_mode.h"

typedef struct igt_3dlut_norm {
	struct drm_color_lut32 lut[4913];
} igt_3dlut_norm_t;

struct igt_color_lut_float {
	float red;
	float green;
	float blue;
};

typedef struct igt_3dlut {
	struct igt_color_lut_float lut[4913];
} igt_3dlut_t;

/*
 * A 3D LUT table with 17x17x17 entries for Traversal order RGB.
 * It can be generated by scripts/convert_3dlut.py
 */
extern const igt_3dlut_t igt_3dlut_17_rgb;

#endif
